# -*- coding: utf-8 -*-
"""demo_project_house_prices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m3ERTFvewZXfwoc5VYSMPIwLGZUMoRFl
"""

import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

df = pd.read_csv(r'/content/homeprices.csv')
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area')
plt.ylabel('price')
plt.scatter(df.area,df.price,color='red',marker='.')

new_df = df.drop('price',axis='columns')
df

Price = df.price
Price

reg = linear_model.LinearRegression()
reg.fit(new_df,Price)

reg.predict([[3300]])

#reg.coef_

reg.predict([[5000]])

plt.xlabel('area',fontsize=20)
plt.ylabel('price',fontsize=20)
plt.scatter(df.area,df.price,color='red',marker='+')
plt.plot(df.area,reg.predict(df[['area']]),color='blue')